require('leap').set_default_keymaps()
-- require('leap').setup {
  -- max_aot_targets = nil,
  -- highlight_unlabeled = false,
  -- case_sensitive = false,
  -- -- Groups of characters that should match each other.
  -- -- E.g.: { "([{<", ")]}>", "'\"`", }
  -- character_classes = {},
  -- -- Leaving the appropriate list empty effectively disables "smart" mode,
  -- -- and forces auto-jump to be on or off.
  -- safe_labels = { . . . },
  -- labels = { . . . },
  -- -- These keys are captured directly by the plugin at runtime.
  -- special_keys = {
  --   eol           = '<space>',
  --   repeat_search = '<enter>',
  --   next_match    = '<enter>',
  --   prev_match    = '<tab>',
  --   next_group    = '<space>',
  --   prev_group    = '<tab>',
  -- },
-- }
